
version: "3.8"

services:
  
  # Service pour l'API Gateway
  apigateway:
    build:
      context: ./apiGateway
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend

  # Service pour le premier contrôleur REST (restctrl1)
  restctrl1:
    build:
      context: ./serviceRest1
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_APPLICATION_NAME=ctrlrest1
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rest1_database   # Utilisation du nom du service mysql
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=emf123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql
    networks:
      - backend

  # Service pour le deuxième contrôleur REST (restctrl2)
  restctrl2:
    build:
      context: ./serviceRest2
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - SPRING_APPLICATION_NAME=ctrlrest2
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rest1_database   # Utilisation du nom du service mysql
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=emf123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql
    networks:
      - backend

  # Service pour la base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: projet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: emf123  # Utilisation de la variable correcte pour le mot de passe root
      MYSQL_DATABASE: rest1_database
    ports:
      - "3309:3306"  # Port mappé entre l'hôte (3309) et le conteneur (3306)
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
