server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: rest1-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/rest1/**
        - id: rest2-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/rest2/**
